<?php
include '../../config/dbfetch.php';
include('../../pages/services/fpdf.php');

if (isset($_GET['id'])) {
    $requestId = $_GET['id'];

    $stmt = $pdo->prepare("SELECT * FROM residency_requests WHERE id = :id AND status = 'Approved'");
    $stmt->execute([':id' => $requestId]);
    $request = $stmt->fetch();

    if (!$request) {
        echo "No approved request found.";
        exit;
    }

    $full_name = $request['first_name'] . ' ' . $request['middle_name'] . ' ' . $request['last_name'];
    $barangay = $request['barangay'];
    $city = $request['city'];
    $purpose = $request['purpose'];
    $date_issued_day = date("j");
    $date_issued_month = date("F");
    $date_issued_year = date("Y");
}

class PDF extends FPDF {
    function Header() {
        $this->SetFont('Arial', 'B', 14);
        $this->Cell(0, 10, 'BARANGAY CERTIFICATION', 0, 1, 'C');
        $this->Ln(5);
    }

    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'Generated by UBISH', 0, 0, 'C');
    }

    function Body($full_name, $barangay, $city, $purpose, $date_issued_day, $date_issued_month, $date_issued_year) {
        $this->SetFont('Arial', '', 12);

        $content = "This is to certify that $full_name, a resident of $barangay, $city, has been residing in this area.\n\n";
        $content .= "This is to certify further that Mr./Ms. $full_name is of good community standing and a law-abiding citizen with no criminal offense/activities on record in this office.\n\n";
        $content .= "This certification is issued upon the request of Mr./Ms. $full_name relative to his application to the $purpose.\n\n";
        $content .= "Issued on this $date_issued_day day of $date_issued_month $date_issued_year.\n\n";
        $content .= "____________________________\nBARANGAY CHAIRMAN\n(Signature over printed name)";

        $this->MultiCell(0, 10, $content);
    }
}

$pdf = new PDF();
$pdf->AddPage();
$pdf->Body($full_name, $barangay, $city,  $purpose, $date_issued_day, $date_issued_month, $date_issued_year);
$pdf->Output('I', 'barangay_certification.pdf');
?>
